services:
  - type: web
    name: mutual-fund-analyzer # You can change this name in Render UI
    env: docker # Specify Docker environment
    plan: free # Or your desired plan
    region: oregon # Or your preferred region
    # buildCommand is not needed for Docker, Render uses Dockerfile
    # startCommand is defined in the Dockerfile CMD
    # Remove Python specific envVars
    # envVars:
    #   - key: PYTHON_VERSION
    #     value: 3.11
    #   - key: FLASK_ENV
    #     value: production
    # Docker specific settings (optional, but good practice)
    dockerfilePath: ./Dockerfile # Path to your Dockerfile
    # You might need to set other envVars here if your app needs them (e.g., database URLs)

